### ISSUE TITLE
train.rs unused variable `r`

### ISSUE THREAD

**Issue by jpp-0** [ronniec95/xladd-derive#2]
`rustc 1.46.0 (04488afe3 2020-08-24)`

When following `examples/train.rs` I am encountering the below compilation warning. This means registration doesn't occur.
It seems registration of non-Array2 functions works fine however.

I would appreciate any advice & thanks in advance 👍 

```
warning: unused variable: `r`
  --> src\lib.rs:58:9
   |
58 |     let r = Reg::new();
   |         ^ help: if this is intentional, prefix it with an underscore: `_r`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.80s
```

https://github.com/ronniec95/xladd-derive/blob/3ebe58438206960c3c7acd4cdc49adcc61515a69/examples/train.rs#L49-L62

**Comment by ronniec95** [comment]
Hi @jpp-0, I think I may have missed an instruction here

In your own cargo.toml file you should have something like

```
[dependencies]
xladd-derive="0.3.2"
xladd = { git ="https://github.com/ronniec95/xladd", features=["use_ndarray"] }
```

If the `features=["use_ndarray"]` is missing then the line with register_add_f64_2 is never compiled which is why the warning appears. Hope that makes sense.

**Comment by jpp-0** [comment]
Hi @ronniec95 
Thanks for the tip

The bit I missed was having to define the feature in my own `Cargo.toml` as well.
Maybe one to update in the readme
Cheers
