### ISSUE TITLE
how to call the function in vba?

### ISSUE THREAD

**Issue by GentleVincent** [ronniec95/xladd-derive#3]
thank you for the great crate, can you show a example about how to call the function in vba? I don't know how to call the function, thanks!

**Comment by ronniec95** [comment]
Hi @GentleVincent.

Check your `Cargo.toml ` has

```
[lib]
crate-type = ["cdylib"]
```

Once you've created the library file, you need to enable it in Excel.

Go to **File/Options/Add-ins/Manage Excel Add-ins/Browse**

![image](https://user-images.githubusercontent.com/888536/95971858-a6bf9500-0e09-11eb-9d79-5825aa0c1440.png)

Find the <my_addin>.dll

Once that's done you should go to any cell in Excel and type `=xl_<my function name>(...)`

![2020-10-14 (2)](https://user-images.githubusercontent.com/888536/95971997-d5d60680-0e09-11eb-8a8a-202aec2a12c4.png)

Let me know if this helps or I need to add further instructions

Thanks

**Comment by GentleVincent** [comment]
Thanks for your reply, I followed your step, it still doesn't work, I don't know if I miss any...

below is cargo.toml
![image](https://user-images.githubusercontent.com/49094111/96057096-bea32180-0eba-11eb-9531-0727a45d9bf6.png)

below is lib.rs the same as your example
![image](https://user-images.githubusercontent.com/49094111/96057190-f4e0a100-0eba-11eb-9c6a-09cb92abd532.png)

then using "cargo build" to build a "rustlib.dll" file.

Excel Add-ins, in this dialog, the default file type is *.xll but not *.dll,  so I select "All Files (*.*) and select the "rustlib.dll"
![image](https://user-images.githubusercontent.com/49094111/96057345-5a349200-0ebb-11eb-98d7-70f9042796e2.png)

then, run the function xlAutoOpen in VBA, and the return value is 1

![vba](https://user-images.githubusercontent.com/49094111/96057792-4f2e3180-0ebc-11eb-97f3-849445cfe064.JPG)
![image](https://user-images.githubusercontent.com/49094111/96057819-5bb28a00-0ebc-11eb-827f-08590bb38be7.png)

I think I have finished all the steps, so I try to use the function in Excel, but I can't find any function,
![image](https://user-images.githubusercontent.com/49094111/96057896-8f8daf80-0ebc-11eb-8941-dddce85ab429.png)

Please help to have a look if I missing something, thanks a lot!

**Comment by ronniec95** [comment]
Hi @GentleVincent 

Just two things that might be an issue

In the lib.rs, you have

```
#[no_mangle]
pub extern "stdcall" fn xlAutoOpen() -> i32 {
    let r = Reg::new();
    #[cfg(feature="use_ndarray")]
    register_add_f64_2(&r);
    1
}
```

but you have not enabled that feature in your Cargo.toml. You need to add this:

```
default = ["use_ndarray"]


[dependencies]
ndarray = "0.13.1" 
```

If you don't want to use ndarray (or make it conditional), you can use 

```
default = ["use_ndarray"]
use_ndarray = ["ndarray"]
ndarray = {version="0.13.1" optional="true"} 
```

but this is more about Cargo.toml incantations.

**Comment by GentleVincent** [comment]
@ronniec95 ， need to consult you again! there are some errors again, I tried four different types of cargo.toml.

type 1:
![image](https://user-images.githubusercontent.com/49094111/96197373-76503600-0f84-11eb-84a6-b3d28c456de2.png)

error as below:
![image](https://user-images.githubusercontent.com/49094111/96197505-e5c62580-0f84-11eb-9ea2-feca3ce40b4b.png)


type 2:
![image](https://user-images.githubusercontent.com/49094111/96197560-055d4e00-0f85-11eb-9183-1b3d9a37c9ab.png)

error as below:
![image](https://user-images.githubusercontent.com/49094111/96197591-173ef100-0f85-11eb-90cd-9dda30bd491b.png)

type 3:
![image](https://user-images.githubusercontent.com/49094111/96197626-33429280-0f85-11eb-8c07-ca5a8460709e.png)

error as below:
![image](https://user-images.githubusercontent.com/49094111/96197637-43f30880-0f85-11eb-8f78-a8fc713826dc.png)

type 4:
![image](https://user-images.githubusercontent.com/49094111/96197682-5a995f80-0f85-11eb-83b3-2ceca987d2bd.png)

error as below:
![image](https://user-images.githubusercontent.com/49094111/96197710-6be26c00-0f85-11eb-95b3-3ef6777b336d.png)

please help to have a look if I missing something again.   Thanks in advance!

**Comment by ronniec95** [comment]
Hi @GentleVincent 

You're `Cargo.toml `has mixed all it's sections together with dependencies and default features being interleaved which is why it's a bit of a mess and cargo can't understand it.

Also I noted you didn't fix the typing error. `"invalid string:true expected boolean"` suggests getting rid of the quotes.

I think you need to familiarise yourself with `Cargo.toml `and all it's various directives in order to get more familiar with Rust and it's build system. It's not complicated but there is a structure to it


The first issue is just a warning, and a correct one. It's saying that given you don't have ndarray enabled the ndarray functions are not being registered. This is good. Try to enable the simple non-ndarray functions first and get that workflow working.

Try to write it like this

```
[features]
default = ["use_ndarray"]
use_ndarray = ["ndarray"]

[dependencies] # type 3 and 4 error - don't mix the sections
ndarray={ version="0.13", features=["approx"]  optional=true } # type 1 & 2 error, fix your types
```

If you or anyone can suggest another way of passing in 2d arrays that would be really interesting.

Hope this helps

**Comment by GentleVincent** [comment]
@ronniec95 Thank you! I just a rust beginner, I am learning rust and cargo. 
I changed the contents of cargo.toml, but still can't find the "correct way".
![image](https://user-images.githubusercontent.com/49094111/96389490-78afcb80-11e2-11eb-83dc-07cd7fb56a00.png)

![image](https://user-images.githubusercontent.com/49094111/96389514-99782100-11e2-11eb-9821-cc9bf6058956.png)

**Comment by ronniec95** [comment]
Would you mind sending me the complete project Cargo.toml and lib.rs and I can have a quick look. I'm not sure if it's me misunderstanding something.

**Comment by GentleVincent** [comment]
Thanks @ronniec95 , it's very grateful for your help, attached is a zip 
file includes lib.rs and cargo.toml, please help to have a check, thank you in advance!

[lib & cargo.zip](https://github.com/ronniec95/xladd-derive/files/5405416/lib.cargo.zip)

**Comment by ronniec95** [comment]
Hi @GentleVincent 

There's nothing wrong in you cargo.toml nor lib.rs. The warnings are just that you are not doing anything with the arguments passed in.

For example you have

```
fn add_f64_2(a: Array2<f64>) -> Result<Array2<f64>, Box<dyn std::error::Error>> {
    Ok(Array2::from_shape_elem[2,2], 0.0f64))
}
```

and the warning is that `a is not being used` which is true, you aren't using it

If you add some logic that uses `a`

```
fn add_f64_2(a: Array2<f64>) -> Result<Array2<f64>, Box<dyn std::error::Error>> {
    let result = a.iter().map(|v| v + 5.0).collect::<Vec<_>>();
    Ok(Array2::from_shape_vec([result.len(), 1], result).unwrap())
}
```
then the warning will go away. This will add 5.0 to every value in the array and return in row format.

Hope that helps.

I've also updated xladd-derive to **0.4** which gives some additional debugging features.

**Comment by GentleVincent** [comment]
Thank you @ronniec95 
I don’t know if I used wrong registration method, I can’t find any UDF function in excel.
![image](https://user-images.githubusercontent.com/49094111/96661120-ee9c6a00-137d-11eb-9d4d-eb8685df0a48.png)

a.	my office version is 2010 and office 365, 32bit, the .dll file builded by rust is also 32bit;
b.	In lib.rs, I didn’t change anything of the register function “xlAutoOpen”;
![image](https://user-images.githubusercontent.com/49094111/96661176-0d026580-137e-11eb-835d-9052260bf110.png)

c.	In excel VBA, below codes used to register the function when WorkBook opened;
![image](https://user-images.githubusercontent.com/49094111/96661274-4509a880-137e-11eb-9282-b7ffa548eeb8.png)

**Comment by ronniec95** [comment]
Hi @GentleVincent 

That is not how to register UDF functions in Excel. 

In my first reply at the top I registered using the File/Options/Addins

![image](https://user-images.githubusercontent.com/888536/96709051-05e55280-1392-11eb-9389-e1bc19f614a3.png)

I did not use VBA. UDF's are registered on Excel Open, not workbook.

Also if you look at

`#[xl_func(category = "OptionPricing", prefix = "my", rename = "baz")]`

The function is called "my_baz"; and using it works fine.

![2020-10-21 (3)](https://user-images.githubusercontent.com/888536/96709272-61174500-1392-11eb-9946-1e54a5ea01e4.png)

**Comment by GentleVincent** [comment]
@ronniec95 Thanks, you are so nice, helped me a lot. I solved the problem due to I didn't register the function correct. 
as a note:
1. modify the register function with the name of your function in lib.rs.
![image](https://user-images.githubusercontent.com/49094111/96802365-4a2d2d00-143c-11eb-8bc1-7bff82b0a59f.png)
2. add the .dll file to excel addin, the vba needs no modification.
![image](https://user-images.githubusercontent.com/49094111/96802501-8b254180-143c-11eb-9374-31c9d4793040.png)
3. if using the UDF function in VBA:
Application.run("functionName", arg1, arg2, ...)
