### ISSUE TITLE
Excel12v order of arguments

### ISSUE THREAD

**Issue by vron** [ronniec95/xladd-derive#4]
Hi,

Really related to your underlying fork of xladd but was not possible to post issues there. I'm struggling to ensure that usage of the crate will not lead to memory errors since the exccel21v function in entrypoint.rs usses the function call type:

`type EXCEL12PROC = extern "stdcall" fn(
    xlfn: ::std::os::raw::c_int,
    count: ::std::os::raw::c_int,
    rgpxloper12: *const LPXLOPER12,
    xloper12res: LPXLOPER12,
) -> ::std::os::raw::c_int;`

Note in particular the order (xlfn, count, result, ...) whereas in xlcall.h it's defined as:

`int pascal Excel12v(int xlfn, LPXLOPER12 operRes, int count, LPXLOPER12 opers[]);`

Where the order is (xlfn, res, count) which is also how it's document at https://docs.microsoft.com/en-us/office/client-developer/excel/excel4v-excel12v

Am i missing something that makes this work?

**Comment by ronniec95** [comment]
The async is less tested admittedly. The regular non-async code is definitely battle tested - I wrote a commercial product xl8ml.com using this, which has about 100 users who appear satisfied so far...

I'm going to test and get back to you later today.
