### ISSUE TITLE
Enhancement: From Vec/slice of Variant

### ISSUE THREAD

**Issue by vron** [ronniec95/xladd-derive#7]
The original xladd had a Variant method from_array() which allowed construction for 2d arrays of Variants.

This is replaced by the (generally much nicer) implementation of From trait for various types.

However , without using ndarray there seems to be now way to construct a 2d array of varying types - I.e it would be usefull to have a methof similar to:

    impl From<&(&[f64], usize)> for Variant {

But instead for slice of Variants:

    impl From<&(&[Variant], usize)> for Variant {

**Comment by ronniec95** [comment]
Done
